# Environment
env=staging

# Application
base.url=https://projectsphere-8xvr.onrender.com/home
browser=chrome

# Timeouts (seconds)
implicit.wait=15
explicit.wait=30
page.load.wait=60

# Retry
retry.count=3

# Paths
report.path=target/reports/ExtentReport-Staging.html
screenshot.path=target/screenshots
excel.path=src/test/resources/testdata/ProjectSphere_TestDesign.xlsx

# Admin credentials
admin.email=admin@projectsphere.com
admin.password=Admin@123

# Project Manager credentials
pm.email=pm@projectsphere.com
pm.password=PM@123

# Developer credentials
developer.email=developer@projectsphere.com
developer.password=Dev@123
